### PR TITLE
Add detection for if flag counter has loaded

### PR DESCRIPTION
**Pull request by dkay0670**
Add detection for if flag counter has loaded

### CODE REVIEW

**Comment by dkay0670** [comment]
You should probably test this on the site itself in dev, I only tested with a userscript on my client

**Comment by HIDEN64** [comment]
It had a bug where the notice appeared at all times, which I mostly fixed in b5f2712. Now it appears when loading/when loading fails, and disappears when loading is finished.
Not ideal, but eh, it works.

**Comment by dkay0670** [comment]
just add display: none to the element itself in the html

**Comment by dkay0670** [comment]
oh wait that won't work because it always starts at 0

**Comment by dkay0670** [comment]
I'll see if I can find a more elegant fix after class

**Comment by HIDEN64** [comment]
A more elegant fix was added in 2748cf5

Adding this as a note.

**Pull request merged**
